# Generated by Django 5.0.2 on 2024-02-21 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corporations', '0001_initial'),
        ('specialist_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doomtrooper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=2000)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doomtroopers', to='corporations.corporation')),
                ('specialist_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doomtroopers', to='specialist_types.specialisttype')),
            ],
        ),
    ]
