# Generated by Django 5.0.2 on 2024-03-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dark_legion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='darklegion',
            name='subheading',
            field=models.CharField(default='1 Legionnaire', max_length=550),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='darklegion',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
