# Generated by Django 4.2.24 on 2025-12-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dark_legion', '0003_alter_darklegion_subheading'),
    ]

    operations = [
        migrations.AddField(
            model_name='darklegion',
            name='choice',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='darklegion',
            name='draw_one_more',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='darklegion',
            name='remove_after_drawing',
            field=models.BooleanField(default=False),
        ),
    ]
