# Generated by Django 4.2.24 on 2025-12-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dark_legion', '0004_darklegion_choice_darklegion_draw_one_more_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='darklegion',
            name='stop_drawing',
            field=models.BooleanField(default=False),
        ),
    ]
