# Generated by Django 5.0.2 on 2024-02-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle_reports', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battlereport',
            old_name='corportations_playing',
            new_name='corporations_playing',
        ),
    ]
