# Generated by Django 5.0.2 on 2024-02-21 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battle_reports', '0001_initial'),
        ('corporations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation_level', models.PositiveIntegerField()),
                ('exp_above_level', models.PositiveIntegerField(default=0)),
                ('battle_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='battle_reports.battlereport')),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='corporations.corporation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
