# Generated by Django 5.0.2 on 2024-02-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doomtroopers', '0001_initial'),
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='doomtroopers_used',
            field=models.ManyToManyField(blank=True, related_name='games_used_in', to='doomtroopers.doomtrooper'),
        ),
    ]
