# Generated by Django 5.0.2 on 2024-03-07 18:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0001_initial'),
        ('games', '0001_initial'),
        ('levels', '0003_alter_level_additional_setup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameSetup',
            new_name='Game',
        ),
    ]
