# Generated by Django 5.0.2 on 2024-03-14 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_gamesetup_game'),
        ('levels', '0003_alter_level_additional_setup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='mission',
        ),
        migrations.AddField(
            model_name='game',
            name='mission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_setups', to='levels.level'),
            preserve_default=False,
        ),
    ]
