# Generated by Django 5.0.2 on 2024-03-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='additional_setup',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
