# Generated by Django 4.2.24 on 2025-12-28 11:30

from django.db import migrations, models
import levels.models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_alter_level_additional_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='map_tiles',
            field=models.JSONField(blank=True, default=levels.models.Level.default_map),
        ),
    ]
